#!/usr/bin/env bash
# AutoGrade setup — macOS, Linux, and Git Bash on Windows.
#
#   ./setup.sh
#
# Creates .env with real generated secrets, asks the few questions that
# cannot be guessed, and starts everything. Safe to re-run: it never
# overwrites an existing .env without asking.
set -euo pipefail

BOLD=$(printf '\033[1m'); GREEN=$(printf '\033[32m')
YELLOW=$(printf '\033[33m'); RED=$(printf '\033[31m'); OFF=$(printf '\033[0m')

say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$OFF" "$*"; }
die()  { printf '%s✗%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }

say ""
say "${BOLD}AutoGrade setup${OFF}"
say "==============="
say ""

# ---------------------------------------------------------------- checks
command -v docker >/dev/null 2>&1 || die \
  "Docker is not installed. Get it from https://docs.docker.com/get-docker/ then run this again."
docker compose version >/dev/null 2>&1 || die \
  "Docker is installed but 'docker compose' is not available. Update Docker Desktop."
docker info >/dev/null 2>&1 || die \
  "Docker is installed but not running. Start Docker Desktop, wait for the whale icon to settle, then run this again."
ok "Docker is installed and running"

# A secret generator that does not assume Python is installed.
gen() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\n=+/' | cut -c1-"${1:-48}"
  else
    head -c 200 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-"${1:-48}"
  fi
}

# ------------------------------------------------------------------ .env
if [ -f .env ]; then
  warn "A .env file already exists."
  read -r -p "  Keep it and just (re)start AutoGrade? [Y/n] " keep
  case "${keep:-Y}" in
    [Nn]*) mv .env ".env.backup.$(date +%Y%m%d%H%M%S)"
           say "  Old .env moved aside." ;;
    *)     SKIP_ENV=1 ;;
  esac
fi

if [ -z "${SKIP_ENV:-}" ]; then
  say ""
  say "${BOLD}A few questions.${OFF} Press Enter to accept the [default]."
  say ""

  read -r -p "Web address people will use [localhost]: " HOSTNAME_IN
  HOSTNAME_IN=${HOSTNAME_IN:-localhost}

  ACME_EMAIL_IN=""
  if [ "$HOSTNAME_IN" != "localhost" ]; then
    read -r -p "Email for certificate expiry warnings: " ACME_EMAIL_IN
  fi

  say ""
  say "Which AI should grade?"
  say "  1) OpenAI          (needs an API key, best quality)"
  say "  2) Claude          (needs an API key)"
  say "  3) Local model     (Ollama on this machine — no per-use cost)"
  read -r -p "Choose 1, 2 or 3 [1]: " PROVIDER_CHOICE
  case "${PROVIDER_CHOICE:-1}" in
    2) PROVIDER=anthropic; read -r -s -p "Paste your Anthropic API key: " KEY; echo ;;
    3) PROVIDER=local;     KEY="" ;;
    *) PROVIDER=openai;    read -r -s -p "Paste your OpenAI API key: " KEY; echo ;;
  esac

  OLLAMA_URL="http://host.docker.internal:11434/v1"
  OLLAMA_MODEL="qwen2.5-coder:7b"
  if [ "$PROVIDER" = "local" ]; then
    read -r -p "Ollama model name [$OLLAMA_MODEL]: " M
    OLLAMA_MODEL=${M:-$OLLAMA_MODEL}
  fi

  say ""
  say "Generating secrets..."
  SECRET_KEY=$(gen 48)
  CRED_KEY=$(gen 48)
  PG_PASSWORD=$(gen 24)

  cat > .env <<ENVEOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file private. It is already in .gitignore.

ENVIRONMENT=production
PUBLIC_HOSTNAME=${HOSTNAME_IN}
ACME_EMAIL=${ACME_EMAIL_IN}
CORS_ORIGINS=https://${HOSTNAME_IN}

# --- secrets: do not share, do not change once in use ---
SECRET_KEY=${SECRET_KEY}
CREDENTIAL_ENCRYPTION_KEY=${CRED_KEY}
POSTGRES_PASSWORD=${PG_PASSWORD}
DATABASE_URL=postgresql+psycopg2://autograde:${PG_PASSWORD}@db:5432/autograde

# --- who may create an account ---
# The first account created becomes the administrator. After that, accounts
# are made by the administrator under Settings -> Account.
ALLOW_OPEN_REGISTRATION=false

# --- AI ---
LLM_PROVIDER=${PROVIDER}
OPENAI_API_KEY=$([ "$PROVIDER" = "openai" ] && printf '%s' "$KEY")
OPENAI_BASE_URL=
OPENAI_GRADING_MODEL=gpt-4o
OPENAI_RUBRIC_MODEL=gpt-4o-mini
ANTHROPIC_API_KEY=$([ "$PROVIDER" = "anthropic" ] && printf '%s' "$KEY")
ANTHROPIC_GRADING_MODEL=claude-opus-5
ANTHROPIC_RUBRIC_MODEL=claude-opus-5
LOCAL_BASE_URL=${OLLAMA_URL}
LOCAL_API_KEY=not-needed
LOCAL_MODEL=${OLLAMA_MODEL}
LLM_TIMEOUT_SECONDS=120
LLM_MAX_RETRIES=3

# --- uploads ---
UPLOAD_DIR=/app/uploads
MAX_FILE_SIZE_MB=50
MAX_REQUEST_BODY_MB=300

# --- backups ---
BACKUP_INTERVAL_HOURS=24
BACKUP_RETENTION_DAYS=30

# --- Canvas (optional; each instructor can also connect their own) ---
CANVAS_BASE_URL=
CANVAS_API_TOKEN=
ENVEOF

  chmod 600 .env 2>/dev/null || true
  ok "Wrote .env (secrets generated, file kept private)"
fi

# ------------------------------------------------------------------ ports
if command -v curl >/dev/null 2>&1; then
  if curl -sS -o /dev/null --max-time 2 http://localhost:80 2>/dev/null; then
    warn "Something is already answering on port 80 (Apache? IIS? Skype?)."
    warn "If startup fails, see RUN_AND_SHARE.md section 10 to move the ports."
  fi
fi

# ------------------------------------------------------------------ start
say ""
say "${BOLD}Building and starting.${OFF} First run downloads a lot — 5-10 minutes is normal."
say ""
docker compose -f docker-compose.prod.yml up -d --build

say ""
say "Waiting for AutoGrade to come up..."
for _ in $(seq 1 60); do
  if curl -skf https://localhost/api/health >/dev/null 2>&1 \
     || curl -sf http://localhost/api/health >/dev/null 2>&1; then
    break
  fi
  sleep 3
done

say ""
if docker compose -f docker-compose.prod.yml ps --status running \
     --format '{{.Service}}' 2>/dev/null | grep -q api; then
  HOST_SHOWN=$(grep '^PUBLIC_HOSTNAME=' .env | cut -d= -f2)
  ok "AutoGrade is running."
  say ""
  say "  ${BOLD}Open:${OFF}  https://${HOST_SHOWN}"
  say ""
  say "  The first account you create becomes the administrator."
  say "  Create yours now, before giving the address to anyone else."
  say ""
  say "  Useful commands:"
  say "    docker compose -f docker-compose.prod.yml ps        # what's running"
  say "    docker compose -f docker-compose.prod.yml logs -f   # watch the logs"
  say "    docker compose -f docker-compose.prod.yml stop      # stop it"
  say ""
  [ "$HOST_SHOWN" = "localhost" ] && warn \
    "On 'localhost' the browser will warn about the certificate. That is expected. Click Advanced -> Proceed."
else
  die "Something did not start. Run: docker compose -f docker-compose.prod.yml logs"
fi
