# AutoGrade setup - Windows PowerShell.
#
#   Right-click this file -> "Run with PowerShell"
#   or, in a PowerShell window:  .\setup.ps1
#
# Creates .env with real generated secrets, asks the few questions that
# cannot be guessed, and starts everything. Safe to re-run.

$ErrorActionPreference = "Stop"

function Say  { param($m) Write-Host $m }
function OK   { param($m) Write-Host "OK  $m" -ForegroundColor Green }
function Warn { param($m) Write-Host "!   $m" -ForegroundColor Yellow }
function Die  { param($m) Write-Host "X   $m" -ForegroundColor Red; exit 1 }

Say ""
Say "AutoGrade setup"
Say "==============="
Say ""

# ------------------------------------------------------------- checks
try { docker --version | Out-Null } catch {
    Die "Docker is not installed. Get Docker Desktop from https://docs.docker.com/get-docker/ then run this again."
}
# Find Compose. Normally `docker compose`, but fall back to the standalone
# binary and then to the plugin Docker Desktop installs, rather than telling
# someone to reinstall the Docker they already have.
$script:Compose = $null
function Test-Compose {
    param($Exe, $Args)
    try {
        & $Exe @Args version 2>&1 | Out-Null
        return $LASTEXITCODE -eq 0
    } catch { return $false }
}
if (Test-Compose "docker" @("compose")) {
    $script:Compose = @("docker", "compose")
} elseif (Test-Compose "docker-compose" @()) {
    $script:Compose = @("docker-compose")
} else {
    $plugin = Join-Path $env:ProgramFiles "Docker\Docker
esources\cli-plugins\docker-compose.exe"
    if (Test-Path $plugin) { $script:Compose = @($plugin) }
}
if (-not $script:Compose) {
    Die "Docker is installed but Compose is not. Install Docker Desktop, which includes it: https://docs.docker.com/get-docker/"
}
$ComposeShown = ($script:Compose -join " ") + " -f docker-compose.prod.yml"

function Invoke-Compose {
    $exe = $script:Compose[0]
    $pre = @($script:Compose[1..($script:Compose.Count - 1)])
    & $exe @pre @args
}
try { docker info 2>&1 | Out-Null; if ($LASTEXITCODE -ne 0) { throw } } catch {
    Die "Docker Desktop is installed but not running. Start it, wait for the whale icon to stop animating, then run this again."
}
OK "Docker is installed and running"

function New-Secret {
    param([int]$Length = 48)
    $bytes = New-Object byte[] 64
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    ([Convert]::ToBase64String($bytes) -replace '[^A-Za-z0-9]', '').Substring(0, $Length)
}

# --------------------------------------------------------------- .env
$skipEnv = $false
if (Test-Path .env) {
    Warn "A .env file already exists."
    $keep = Read-Host "  Keep it and just (re)start AutoGrade? [Y/n]"
    if ($keep -match '^[Nn]') {
        Move-Item .env ".env.backup.$(Get-Date -Format yyyyMMddHHmmss)"
        Say "  Old .env moved aside."
    } else { $skipEnv = $true }
}

if (-not $skipEnv) {
    Say ""
    Say "A few questions. Press Enter to accept the [default]."
    Say ""

    $hostname = Read-Host "Web address people will use [localhost]"
    if ([string]::IsNullOrWhiteSpace($hostname)) { $hostname = "localhost" }

    $acmeEmail = ""
    if ($hostname -ne "localhost") {
        $acmeEmail = Read-Host "Email for certificate expiry warnings"
    }

    Say ""
    Say "Which AI should grade?"
    Say "  1) OpenAI          (needs an API key, best quality)"
    Say "  2) Claude          (needs an API key)"
    Say "  3) Local model     (Ollama on this machine - no per-use cost)"
    $choice = Read-Host "Choose 1, 2 or 3 [1]"

    $key = ""
    switch ($choice) {
        "2" { $provider = "anthropic"
              $secure = Read-Host "Paste your Anthropic API key" -AsSecureString
              $key = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
                     [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)) }
        "3" { $provider = "local" }
        default { $provider = "openai"
              $secure = Read-Host "Paste your OpenAI API key" -AsSecureString
              $key = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
                     [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)) }
    }

    $ollamaModel = "qwen2.5-coder:7b"
    if ($provider -eq "local") {
        $m = Read-Host "Ollama model name [$ollamaModel]"
        if (-not [string]::IsNullOrWhiteSpace($m)) { $ollamaModel = $m }
    }

    Say ""
    Say "Generating secrets..."
    $secretKey  = New-Secret 48
    $credKey    = New-Secret 48
    $pgPassword = New-Secret 24

    $openaiKey    = if ($provider -eq "openai")    { $key } else { "" }
    $anthropicKey = if ($provider -eq "anthropic") { $key } else { "" }

    $env_content = @"
# Generated by setup.ps1 on $(Get-Date -Format s)
# Keep this file private. It is already in .gitignore.

ENVIRONMENT=production
PUBLIC_HOSTNAME=$hostname
ACME_EMAIL=$acmeEmail
CORS_ORIGINS=https://$hostname

# --- secrets: do not share, do not change once in use ---
SECRET_KEY=$secretKey
CREDENTIAL_ENCRYPTION_KEY=$credKey
POSTGRES_PASSWORD=$pgPassword
DATABASE_URL=postgresql+psycopg2://autograde:$pgPassword@db:5432/autograde

# --- who may create an account ---
# The first account created becomes the administrator. After that, accounts
# are made by the administrator under Settings -> Account.
ALLOW_OPEN_REGISTRATION=false

# --- AI ---
LLM_PROVIDER=$provider
OPENAI_API_KEY=$openaiKey
OPENAI_BASE_URL=
OPENAI_GRADING_MODEL=gpt-4o
OPENAI_RUBRIC_MODEL=gpt-4o-mini
ANTHROPIC_API_KEY=$anthropicKey
ANTHROPIC_GRADING_MODEL=claude-opus-5
ANTHROPIC_RUBRIC_MODEL=claude-opus-5
LOCAL_BASE_URL=http://host.docker.internal:11434/v1
LOCAL_API_KEY=not-needed
LOCAL_MODEL=$ollamaModel
LLM_TIMEOUT_SECONDS=120
LLM_MAX_RETRIES=3

# --- uploads ---
UPLOAD_DIR=/app/uploads
MAX_FILE_SIZE_MB=50
MAX_REQUEST_BODY_MB=300

# --- backups ---
BACKUP_INTERVAL_HOURS=24
BACKUP_RETENTION_DAYS=30

# --- Canvas (optional; each instructor can also connect their own) ---
CANVAS_BASE_URL=
CANVAS_API_TOKEN=
"@
    # UTF8 without BOM - Docker will not parse a BOM in an env file.
    [IO.File]::WriteAllText("$PWD\.env", $env_content,
                            (New-Object Text.UTF8Encoding $false))
    OK "Wrote .env (secrets generated)"
}

# --------------------------------------------------------------- ports
$busy = Get-NetTCPConnection -LocalPort 80, 443 -State Listen -ErrorAction SilentlyContinue
if ($busy) {
    Warn "Ports 80/443 are already in use (Apache? IIS? XAMPP?)."
    Warn "If startup fails, change the published ports in docker-compose.prod.yml."
}

# --------------------------------------------------------------- start
Say ""
Say "Building and starting. First run downloads a lot - 5-10 minutes is normal."
Say ""
Invoke-Compose -f docker-compose.prod.yml up -d --build
if ($LASTEXITCODE -ne 0) { Die "Startup failed. Run: $ComposeShown logs" }

Say ""
Say "Waiting for AutoGrade to come up..."
$ready = $false
foreach ($i in 1..60) {
    try {
        Invoke-WebRequest -Uri "https://localhost/api/health" -SkipCertificateCheck `
            -TimeoutSec 3 -UseBasicParsing | Out-Null
        $ready = $true; break
    } catch { Start-Sleep -Seconds 3 }
}

$shown = (Select-String -Path .env -Pattern '^PUBLIC_HOSTNAME=(.*)$').Matches.Groups[1].Value
Say ""
if ($ready) { OK "AutoGrade is running." } else {
    Warn "Started, but the health check did not answer yet. Give it another minute, then check the logs."
}
Say ""
Say "  Open:  https://$shown"
Say ""
Say "  The first account you create becomes the administrator."
Say "  Create yours now, before giving the address to anyone else."
Say ""
Say "  Useful commands:"
Say "    $ComposeShown ps        # what's running"
Say "    $ComposeShown logs -f   # watch the logs"
Say "    $ComposeShown stop      # stop it"
Say ""
if ($shown -eq "localhost") {
    Warn "On 'localhost' the browser warns about the certificate. That is expected - click Advanced, then Proceed."
}
