"""canvas credentials and admin accounts

Revision ID: 07f1debe3df8
Revises: 3f310efeb8b7
Create Date: 2026-09-05 18:51:53.386573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f1debe3df8'
down_revision: Union[str, None] = '3f310efeb8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_hint', sa.String(length=8), nullable=True),
    sa.Column('canvas_user_name', sa.String(length=255), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_credentials_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required: this is NOT NULL and existing
        # installs already have user rows, which would otherwise fail
        # the upgrade. Existing accounts become non-admins; the first
        # account is promoted below so an upgraded instance still has
        # someone who can manage it.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(),
                                      nullable=False,
                                      server_default=sa.false()))

    # ### end Alembic commands ###

    # On an instance that already has users, make the oldest account the
    # administrator so the new account-management screens are reachable
    # without touching the database by hand.
    op.execute(
        "UPDATE users SET is_admin = true WHERE id = ("
        "  SELECT id FROM users ORDER BY created_at LIMIT 1)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('canvas_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_credentials_user_id'))

    op.drop_table('canvas_credentials')
    # ### end Alembic commands ###
