"""per-professor provider credentials

Revision ID: 3f310efeb8b7
Revises: fffe1986931e
Create Date: 2026-09-05 12:25:12.581541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f310efeb8b7'
down_revision: Union[str, None] = 'fffe1986931e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=True),
    sa.Column('key_hint', sa.String(length=8), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_credential')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_provider', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_provider')

    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_user_id'))

    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
