"""grading jobs and login attempts

Revision ID: fffe1986931e
Revises: 53024e9b8b23
Create Date: 2026-09-05 05:20:42.360289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffe1986931e'
down_revision: Union[str, None] = '53024e9b8b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_email_time', ['email', 'attempted_at'], unique=False)
        batch_op.create_index('ix_login_attempts_ip_time', ['ip_address', 'attempted_at'], unique=False)

    op.create_table('grading_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('graded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_jobs_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_grading_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_grading_jobs_active_assignment', ['assignment_id'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_grading_jobs_active_assignment', sqlite_where=sa.text("status IN ('queued', 'running')"), postgresql_where=sa.text("status IN ('queued', 'running')"))
        batch_op.drop_index(batch_op.f('ix_grading_jobs_user_id'))
        batch_op.drop_index('ix_grading_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_grading_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_grading_jobs_assignment_id'))

    op.drop_table('grading_jobs')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_time')
        batch_op.drop_index('ix_login_attempts_email_time')

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
