"""
Safe handling of uploaded student files.

Everything a student uploads is untrusted input. Three rules:

1. The stored filename is generated by us, never taken from the upload.
   A submission called `../../.env` must not be able to escape the
   upload directory.
2. Files live under `<upload_dir>/<assignment_id>/`, so deleting an
   assignment can delete its files without a database query.
3. Size is enforced while streaming, not after. A 10 GB upload must not
   have to land on disk before we reject it.
"""
from __future__ import annotations

import re
import shutil
import unicodedata
import uuid
from pathlib import Path
from typing import BinaryIO

from backend.config import settings
from backend.parsers.base import SUPPORTED_EXTENSIONS

# Read uploads in 1 MB chunks so the size check happens as we go.
CHUNK_SIZE = 1024 * 1024

# Anything outside this set is stripped from a display filename.
_UNSAFE = re.compile(r"[^A-Za-z0-9._-]+")


class FileTooLargeError(ValueError):
    """Raised when an upload exceeds MAX_FILE_SIZE_MB."""


class UnsupportedFileError(ValueError):
    """Raised when an upload has an extension we cannot grade."""


def upload_root() -> Path:
    """The configured upload directory, created if missing."""
    root = Path(settings.upload_dir).resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root


def sanitize_filename(filename: str) -> str:
    """
    Reduce an arbitrary upload name to something safe to display and log.

    Strips directory components, normalises unicode, and collapses
    anything unusual to an underscore. Never returns an empty string.
    """
    # Handle both separators - a Windows client may send either.
    base = filename.replace("\\", "/").split("/")[-1]
    base = unicodedata.normalize("NFKD", base).encode("ascii", "ignore").decode()
    base = _UNSAFE.sub("_", base).strip("._") or "submission"
    return base[:200]


def validate_extension(filename: str) -> str:
    """
    Return the lowercase extension if we can grade it, else raise.

    Checked before anything is written to disk.
    """
    suffix = Path(sanitize_filename(filename)).suffix.lower()
    if suffix not in SUPPORTED_EXTENSIONS:
        raise UnsupportedFileError(
            f"'{suffix or 'no extension'}' is not a supported submission type. "
            f"Accepted: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
        )
    return suffix


def guess_student_name(filename: str) -> str | None:
    """
    Best-effort student name from a filename.

    Canvas exports look like `chenalice_12345_67890_hw3.ipynb`; a manual
    upload is more often `alice_chen_hw3.ipynb`. Both give us something
    better than nothing, and the professor can correct it in the UI.
    """
    stem = Path(sanitize_filename(filename)).stem

    # Canvas: strip the two numeric ids it appends after the name.
    canvas = re.match(r"^([a-zA-Z]+)_(\d+)_(\d+)_", stem)
    if canvas:
        return canvas.group(1).replace("_", " ").title() or None

    # Otherwise take the leading alphabetic words, stopping at the first
    # token that looks like an assignment label (hw3, lab2, assignment1).
    words: list[str] = []
    for part in re.split(r"[._-]+", stem):
        if not part or re.match(r"^(hw|lab|assignment|project|final|midterm|p)\d*$",
                                part, re.I):
            break
        if part.isdigit():
            break
        words.append(part)

    name = " ".join(words).strip().title()
    return name or None


# A student who writes "Name: Jane Doe" / "Student ID: 12345" in a header
# cell is common; read that when the filename tells us nothing.
_NAME_LABEL = re.compile(
    r"\b(?:student\s*name|full\s*name|name|author|submitted\s*by)\b"
    r"\s*[:=\-]\s*([A-Za-z][A-Za-z .'\-]{1,50})",
    re.I,
)
_ID_LABEL = re.compile(
    r"\b(?:student\s*id|student\s*number|matric(?:ulation)?(?:\s*(?:no|number|id))?|"
    r"roll\s*(?:no|number)|registration\s*(?:no|number)|id\s*(?:no|number))\b"
    r"\s*[:#=\-]?\s*([A-Za-z]?\d[A-Za-z0-9\-]{2,19})",
    re.I,
)


def extract_identity_from_parsed(parsed: dict) -> tuple[str | None, str | None]:
    """
    Best-effort student name and id read from a submission's own text.

    Scans the first several cells (headers/markdown are where students put
    their details) for "Name: ..." and "Student ID: ..." style labels. Returns
    (name, student_id); either may be None. Never raises - identity detection
    must not be able to fail an upload.
    """
    chunks: list[str] = []
    for cell in (parsed.get("cells") or [])[:10]:
        source = (cell.get("source") or "").strip()
        if source:
            chunks.append(source)
    text = "\n".join(chunks)[:5000]

    name = None
    match = _NAME_LABEL.search(text)
    if match:
        candidate = re.sub(r"\s+", " ", match.group(1)).strip(" .-'")
        if len(candidate) >= 2 and candidate.lower() not in (
            "name", "student", "here", "the", "your"
        ):
            name = candidate

    student_id = None
    match = _ID_LABEL.search(text)
    if match:
        student_id = match.group(1).strip()

    return name, student_id


def save_upload(
    source: BinaryIO,
    original_filename: str,
    assignment_id: str,
) -> tuple[Path, int, str]:
    """
    Stream an upload to disk under the assignment's folder.

    Returns (path, size_bytes, file_type). Raises UnsupportedFileError or
    FileTooLargeError; on failure nothing is left behind.
    """
    suffix = validate_extension(original_filename)
    max_bytes = settings.max_file_size_mb * 1024 * 1024

    # Directory name is a UUID from our own database, not user input.
    target_dir = upload_root() / str(assignment_id)
    target_dir.mkdir(parents=True, exist_ok=True)

    safe_stem = Path(sanitize_filename(original_filename)).stem
    stored_name = f"{uuid.uuid4().hex[:12]}_{safe_stem}{suffix}"
    target = target_dir / stored_name

    written = 0
    try:
        with target.open("wb") as out:
            while chunk := source.read(CHUNK_SIZE):
                written += len(chunk)
                if written > max_bytes:
                    raise FileTooLargeError(
                        f"{original_filename} exceeds the "
                        f"{settings.max_file_size_mb} MB limit."
                    )
                out.write(chunk)
    except Exception:
        target.unlink(missing_ok=True)
        raise

    if written == 0:
        target.unlink(missing_ok=True)
        raise UnsupportedFileError(f"{original_filename} is empty (0 bytes).")

    file_type = "html" if suffix in (".html", ".htm") else suffix.lstrip(".")
    return target, written, file_type


def delete_assignment_files(assignment_id: str) -> int:
    """
    Remove every stored file for one assignment.

    Returns the number of files deleted. Missing directories are not an
    error - deleting an assignment with no uploads must still succeed.
    """
    target_dir = upload_root() / str(assignment_id)
    if not target_dir.is_dir():
        return 0

    count = sum(1 for p in target_dir.rglob("*") if p.is_file())
    shutil.rmtree(target_dir, ignore_errors=True)
    return count


def delete_file(file_path: str | Path) -> bool:
    """
    Delete one stored submission file.

    Refuses to touch anything outside the upload directory - a corrupted
    `file_path` column must not become an arbitrary-delete primitive.
    """
    path = Path(file_path).resolve()
    root = upload_root()
    if not path.is_relative_to(root):
        raise ValueError(f"Refusing to delete {path}: outside the upload directory")
    if not path.is_file():
        return False
    path.unlink()
    return True
